---
# tasks file for inmotion.nextcloud

#
# Setup
#

- name: (Nextcloud) Install unzip
  package:
    name: unzip
    state: present

#
# Setup
#

- name: (Nextcloud) Create the system user group
  group:
    name: "{{ system_user }}"
    state: present

- name: (Nextcloud) Create the system user account
  user:
    name: "{{ system_user }}"
    group: "{{ system_user }}"

- name: (Nextcloud) Ensure system user home exists
  file:
    path: /home/{{ system_user }}
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: "0711"

- name: (Nextcloud) Ensure tmp exists
  file:
    path: /home/{{ system_user }}/tmp
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: "0711"

#
# Apache
#

- name: (Nextcloud) Include Debian-family tasks
  include: "{{ ansible_os_family }}.yml"
  vars:
    targets:
      - Debian
  when: ansible_os_family in targets

- name: (Nextcloud) Configure httpd mpm module
  template:
    src: etc/httpd/modules.d/00-mpm.conf.j2
    dest: "{{ apache_modules_config_path }}/00-mpm.conf"
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart apache
    - restart php-fpm

- name: (Nextcloud) Create httpd virtual host
  template:
    src: etc/httpd/conf.d/site.conf.j2
    dest: "{{ apache_config_site_path }}/{{ site_domain }}.conf"
  notify:
    - restart apache

#
# PHP
#

- name: (Nextcloud) Place site-specific php-fpm config
  template:
    src: etc/php-fpm.d/site.conf.j2
    dest: "{{ php_fpm_config_pool_path }}/{{ site_domain }}.conf"
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart php-fpm

- name: (Nextcloud) Remove default www pool
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/php/7.0/fpm/pool.d/www.conf
    - /etc/php-fpm.d/www.conf
  notify:
    - restart php-fpm

#
# Nextcloud
#

- name: (Nextcloud) Check for existing Nextcloud installation
  stat:
    path: "{{ nc_system_path }}/config/config.php"
  changed_when: not nextcloud_installed.stat.exists
  ignore_errors: true
  register: nextcloud_installed

- name: (Nextcloud) Install Nextcloud
  include: "nextcloud.yml"
  when: nextcloud_installed.changed

#
# Redis
#

# Redis will be disabled if the host's total memory is <= 1GB
- name: (Redis) Check Memory for Redis inclusion
  set_fact:
    use_redis: false
  when:
    - use_redis is defined
    - use_redis
    - ansible_memtotal_mb <= 1024

- name: (Redis) Configure Redis
  include: "redis.yml"
  when:
    - use_redis is defined
    - use_redis

#
# External primary storage
#

- name: (Redis) Configure external primary storage
  template:
    src: "object_storage/{{ data_storage }}.yml"
    dest: "{{ nc_system_path }}/config/{{ data_storage }}.config.php"
    owner: root
    group: root
    mode: "0644"
  when: data_storage != "data_dir"
